### ISSUE TITLE
[BUG] Failed to unify types InfSet[Int]

### ISSUE THREAD

**Issue by banhday** [informalsystems/apalache#1019]
Snowcat says that types in the attached specification [toyexample.zip](https://github.com/informalsystems/apalache/files/7293249/toyexample.zip) are okay. However, I received the following error message when running the command `apalache-mc check --length=1 toyexample.tla`:
`toyexample.tla:35:30-35:49: type error: Failed to unify types InfSet[Int] and ${rightSetCell.cellType} when rewriting ${state.ex}`

- Apalache version [`apalache-mc version`]: 0.16.2

**Comment by konnov** [comment]
We should definitely improve the error message. The reason for that error is that apalache supports set operations over bounded sets. The following lines are problematic for apalache:

```tla
Time == Nat
TimeNull == -1
TypeOK == clock \in [Proc -> Time \cup {TimeNull}]
```

As an alternative, you could write `Int` instead of `Time` and `{TimeNull}` and add additional constraints, where needed. The trick here is to quantify over a bounded set of values, e.g., over `Proc`, rather than over an infinite set of values, e.g., `Nat \cup {-1}`.

**Comment by thpani** [comment]
This must've been fixed somewhere along the road. It works fine in `v0.25.6-61-g68342fcb8`.
