### ISSUE TITLE
Produce TLC-compatible output

### ISSUE THREAD

**Issue by konnov** [informalsystems/apalache#107]
Since we are producing TLC-compatible counterexamples, we should also think of producing a TLC-compatible log file. That would help a smooth integration in TLA+ Toolbox and other tools.

**Comment by lemmy** [comment]
[MP.java](https://github.com/tlaplus/tlaplus/blob/master/tlatools/src/tlc2/output/MP.java) and [EC.java](https://github.com/tlaplus/tlaplus/blob/master/tlatools/src/tlc2/output/EC.java) are were 99% of the log file code is.  From an SE perspective, it would probably make sense to share MP.java and EC.java between apalache and TLC.

**Comment by konnov** [comment]
We are using `tla2tools.jar` anyways. However, it will give you less flexibility in changing these classes.

**Comment by lemmy** [comment]
If you think about it, the two classes are the only actual encoding (API) of the schema-less/text-based TLC to Toolbox communication protocol.  I would argue that we don't want flexibility here but instead leverage javac to warn us if we effectively break the text protocol.

**Comment by andrey-kuprianov** [comment]
I was considering using the functions in MP.java and EC.java, but then decided not to, because of the following reasons:
 - from the Apalache code structure, only one component now depends on `tlatools.jar`, but the class that needs logging logically belongs to another component. introducing dependency on `tlatools.jar` also there would be a bit overkill.
- most of the functions in those files are very TLC-specific. The overhead of using them is actually much higher, than reproducing the encoding literally -- at the end, it's only output. So, effectively, we become very loosely coupled by the small portion of the text output format that TLC uses, and my feeling is that this is actually better than depending on the internal implementation details of formatting functions.

**Comment by konnov** [comment]
That makes sense. However, we can introduce an adapter class in our codebase, which will be the only class connected to `EC` and `MC` in `tla2tools`. In case of unexpected changes, we can safely introduce a fix in the adapter.

**Comment by lemmy** [comment]
> The overhead of using them is actually much higher, than reproducing the encoding literally -- at the end, it's only output

A ~decade of Toolbox development has taught me the opposite:  The text-based protocol is brittle and difficult to evolve even with just a single back-end (TLC).  Note that if it makes things easier on the apalache end, we can refactor or extract common functionality from MP.java and EC.java.

**Comment by andrey-kuprianov** [comment]
actually what I've said was about producing counterexamples in TLC format. When we come to the general TLC-compatible output, we'll see -- maybe then integrating the functionality of MP/EC.java will pay off...

**Comment by konnov** [comment]
I agree that it is much easier to see breaking changes in the text protocol when our code stops compiling. Having our own copy of text messages just postpones the problem detection when the protocol changes.

**Comment by andrey-kuprianov** [comment]
yes, that's right. probably we should take the route of integrating using an adapter, as you proposed

**Comment by konnov** [comment]
@andrey-kuprianov, are we postponing this one?

**Comment by andrey-kuprianov** [comment]
@konnov yep; we postpone it

**Comment by konnov** [comment]
Closing this issue, as we are not expecting any progress on it.
