### ISSUE TITLE
[BUG] Locally defined polymorphic operators cannot reference parent operator's type variables

### ISSUE THREAD

**Issue by Kukovec** [informalsystems/apalache#1088]
## Description

Whenever a polymorphic operator defines a local LET-IN operator, which is also polymorphic, the inner operator's type annotations are treated as separately quantified and not as references to the parent operator's type variables . 

## Input specification
```
---------- MODULE test ----------

EXTENDS Integers, Apalache

\* @type: (a, a) => a;
F(x,y) ==
  \* @type: Set(a);    
  LET A == {x}
  IN IF y \in A THEN x ELSE y

Init == TRUE

Next == TRUE

Inv == F(1,1) = 1
====================
```

## The command line parameters used to run the tool

`--inv=Inv --length=1`

## Additional context

Tool will not throw, because the operator in question gets removed by inlining, but combining such operators with e.g. folds would result in the same behavior as in #1085.

**Comment by konnov** [comment]
Your understanding is consistent with e.g. Ocaml. This code compiles in OCaml:

```ml
let f: 'a -> 'a -> 'a = fun x -> fun y ->
    let g: 'a -> 'a list = fun z ->
        [z]
    in
    if List.mem y (g x) then x else y
```

Will fix Snowcat.

**Comment by shonfeder** [comment]
Reporting a summary of a discussion on our internal slack.

Iiuc, the OCaml code snippet given by @konnov, does not given an example of a type variable inside a function body referencing the type variables in the function head. Rather, this code snippet compiles because `g` is (correctly) annotated as a function which will take a term of any type '`a` to list of terms of type `'a`. Since the function works for arguments of any type, it will of course also work when applied to `x`, regardless of what type it is. We can make this clear by making the universal quantification over the type variables in `g`'s annotation explicit:

```ocaml
# let f: 'a -> 'a -> 'a = fun x -> fun y ->
    let g: type b. b -> b list = fun z ->
        [z]
    in
    if List.mem y (g x) then x else y
;;
val f : 'a -> 'a -> 'a = <fun>
```

I am unfamiliar with any convention in ML-family languages that allows "normal" (i.e., universally quantified *implicitly*) type variables used in annotations of subexpressions to refer to universally quantified type variables annotating their parent expression. But after, a bit of research, I now know of two examples where special syntax is introduced to enable this kind of thing:


- The "scoped typed variables" extension of GHC:  https://wiki.haskell.org/Scoped_type_variables
- Ocaml's explicit universal type annotation (probably implemented following the previous):

```
utop # let f: type a. a -> a -> a = fun x y ->
  let g: a list = [x] in
  if List.mem y g then x else y
;;
```

If we do introduce this kind of behavior, I suggest we follow that example, otherwise we're liable to end up with behavior that is surprising for anyone used to HM style type annotations.

As Igor noted, this kind of pattern is syntactically familiar to languages that use generics.

**Comment by shonfeder** [comment]
But also, I would expect the example given in the issue body to work anyhow, just as this example works in OCaml:

```ocaml
 # let f: 'a -> 'a -> 'a = fun x y ->
  let g : 'b list = [x] in
  if List.mem y g then x else y
;;
val f : 'b -> 'b -> 'b = <fun>
```

I.e., not because the `a` in `\* @type: Set(a);` refers to the type variable in the annotation of the head (which I'd find surprising), but because they are both universally quantified, and the type variables can be unified during checking here.

**Comment by konnov** [comment]
Have a look at #1104. Your test goes through there.
