### ISSUE TITLE
[BUG] Build error when using `make apalache-jar`

### ISSUE THREAD

**Issue by rodrigo7491** [informalsystems/apalache#1219]
## Description

Building Apalache using `make apalache-jar`, as described in the [documentation](https://apalache.informal.systems/docs/apalache/installation/source.html), leads to the following error:
```
[ERROR] Failed to execute goal on project tla-pp: Could not resolve dependencies for project at.forsyte.apalache:tla-pp:jar:0.19.2-SNAPSHOT: Could not find artifact at.forsyte.apalache:tlair:jar:tests:0.19.2-SNAPSHOT in oss-sonatype (https://oss.sonatype.org/content/repositories/snapshots/) -> [Help 1]
```
Building with `make` works without problems. The problem with `make apalache-jar` happens after running both `mvn clean && mvn package` and `make`.

## Expected behavior

No error.

## System information

- Apalache version [`apalache-mc version`]: v0.19.2
- OS [e.g. Ubuntu Linux or Mac OS, and the current version]: Linux Mint 20.2
- JDK version [e.g. OpenJDK 0.8.0]: openjdk 11.0.13

**Comment by shonfeder** [comment]
Thank you for the report, @rodrigo7491!

The problematic dependency was added in https://github.com/informalsystems/apalache/pull/1191/commits/51228a7a714920d9f3d831880949ce3648901354

Maven apparently ignores building the dependency when `maven.test.skip=true` (as in our `apalache-jar` target), but then still requires the dependency to be present. This appears to be a known issue with maven (since like 2014), the problem and some workarounds are described here:
https://issues.apache.org/jira/browse/MJAR-138?focusedCommentId=16160394&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-16160394

I think I have a way forward for this.

**Comment by konnov** [comment]
I am hitting the same with `mvn package  -Dmaven.test.skip=true`
