### ISSUE TITLE
[FEATURE] Evaluate whether we can make Z3SolverContext tail recursive

### ISSUE THREAD

**Issue by konnov** [informalsystems/apalache#1338]
Related to #1336

**Comment by shonfeder** [comment]
I'm gonna take a quite look at this, as I could use a bit of a clean algorithmic diversion :)

**Comment by shonfeder** [comment]
I had a peek and googled some stuff. afaik, without substantially reworking the whole approach, the only way to eliminate the chance of SO's in `Z3SolverContext` due to the nontailrec call is to use continuation passing (perhaps made cleaner in this case via use of Scala's stdlin trampolining utilities or Scalaz's Free-monad based alternatives). This would mean moving stuff from the call stack to the heap, so we should bear in mind that we'd a slowdown here in return for the added stack safety.

**Comment by konnov** [comment]
Let's close this issue. @shonfeder, thanks for the analysis!
