### ISSUE TITLE
Parallelize unit test runs

### ISSUE THREAD

**Issue by thpani** [informalsystems/apalache#1761]
We currently [disable running some unit tests in parallel](https://github.com/informalsystems/apalache/blob/de1e90b0f01ac84aeb20c64efc74838623c5cb5a/build.sbt#L99) to work around the SANY bug https://github.com/tlaplus/tlaplus/issues/688.

Once that bug is resolved, we should remove `Test / parallelExecution := false` from `build.sbt` to lift the restriction.

**Comment by shonfeder** [comment]
I don't think we'll be able to parallelize the unit tests even once https://github.com/tlaplus/tlaplus/issues/688 is fixed, because Sany seems to rely on a global state, and trying to start two Sany parser sessions concurrently causes the failure noted here: https://github.com/informalsystems/apalache/issues/1114#issuecomment-1180534894

**Comment by thpani** [comment]
To summarize my understanding on this, we'd have to introduce global state in Apalache (like a lock or queue) to sequentialize concurrent calls to SANY. Which should work for the CLI, and server, not sure how the JUnit runner maintains state.

**Comment by shonfeder** [comment]
I prepped the fix for this before seeing that you'd planned to take up on work it, @thpani. Sorry for the race condition on my part!

**Comment by thpani** [comment]
> I prepped the fix for this before seeing that you'd planned to take up on work it, @thpani. Sorry for the race condition on my part!

No worries, I didn't have any cycles for this anyways!
Thanks for picking it up!
