### ISSUE TITLE
Example y2k_overrides.tla does not work

### ISSUE THREAD

**Issue by nano-o** [informalsystems/apalache#1794]
```
apalache-mc check --inv=Safety --length=20 apalache/test/tla/y2k_override.tla
```
produces 
```
...
PASS #7: PreprocessingPass                                        I@22:46:34.645
  > Before preprocessing: unique renaming                         I@22:46:34.645
 > Applying standard transformations:                             I@22:46:34.650
  > PrimePropagation                                              I@22:46:34.651
  > Desugarer                                                     I@22:46:34.652
  > UniqueRenamer                                                 I@22:46:34.654
  > Normalizer                                                    I@22:46:34.656
y2k.tla:25:8-25:17: unexpected expression: undeclared operator BIRTH_YEAR E@22:46:34.668
Unexpected expressions in the specification (see the error messages) E@22:46:34.669
It took me 0 days  0 hours  0 min  0 sec                          I@22:46:34.669
Total time: 0.605 sec                                             I@22:46:34.669
EXITCODE: ERROR (255)
```

**Comment by shonfeder** [comment]
Some initial debugging notes:

Here's the `y2k_override.tla` for reference:

```tla
---------------------------- MODULE y2k_override ----------------------------
(*
 * One way to instantiate constants for apalache is to use the OVERRIDE prefix. 
 *)
 
EXTENDS y2k

OVERRIDE_BIRTH_YEAR == 80
OVERRIDE_LICENSE_AGE == 18

=============================================================================
```

And here's the relevant part of `y2k.tla` (where hitting the error on the last line):

```tla
-------------------------------- MODULE y2k --------------------------------
(* ... *)

EXTENDS Integers
 
CONSTANT
    \* @type: Int;
    BIRTH_YEAR, \* the year to start with, between 0 and 99
    \* @type: Int;
    LICENSE_AGE    \* the minimum age to obtain a license
         
ASSUME(BIRTH_YEAR \in 0..99)              
```

The error is being raised at

https://github.com/informalsystems/apalache/blob/8c15134fe26b4b0551fbf237009c169f9e0ca2a4/tlair/src/main/scala/at/forsyte/apalache/tla/lir/transformations/standard/FlatLanguagePred.scala#L30-L33

Notably, contrary to the comment, this is not a "nullary operator that was declared with let-in", but a constant that should have been set by the override.

I guess the `TlaConstInliner` should have already replaced these values with their expected values by this point, but I haven't figured out how to figure out why that's happening.

**Comment by konnov** [comment]
@Kukovec can you maybe have a look?

**Comment by Kukovec** [comment]
Ok, so the issue was, doing constant initialization via overloading _from another TLA file_ means that instead of `CInit` (which gets produced when you overload from `.cfg`) the values that were previously constants are now floating around as generic operators. `ASSUME` doesn't know this (you're effectively doing something equivelent to `A == 1, ASSUME ( A > 0 )` instead of `CONSTANT A, ASSUME( A > 0)` so you have dangling references to constants (constants, in the `CONSTANT` sense, are _not_ inlined in `ASSUME` statements, because those aren't encoded, see https://apalache.informal.systems/docs/apalache/features.html?#module-level-constructs). I'll push a fix in a few minutes.
