### ISSUE TITLE
Names of assumptions with `ASSUME` are not parsed into the IR

### ISSUE THREAD

**Issue by bugarela** [informalsystems/apalache#1835]
## Description

From all possible TLA+ declarations Apalache parses, `ASSUME` is the only one in which the name is ignored, even tho it is always present in TLA+.

Even if it's not relevant for Apalache, I believe we should parse it and represent it on the IR so it is more consistent. I know this IR is not a public interface for anyone to use yet, but I'm writing a parser for it and would not like to have a special case for handling this silly case.

## Input specification

```tla
---------------------------- MODULE AssumeExample----------------------------
CONSTANT N

ASSUME myName == N = TRUE
=============================================================================
```

## The command line parameters used to run the tool

```
apalache-mc parse --output=AssumeExample.json AssumeExample.tla
```

## Expected behavior

At `AssumeExample.json`:

```
{
  "source": {
    "filename": "AssumeExample",
    "from": {
      "line": 4,
      "column": 1
    },
    "to": {
      "line": 4,
      "column": 25
    }
  },
  "type": "Untyped",
  "kind": "TlaAssumeDecl",
  "name": "myName", // <-------- this line is currently missing
  "body": { ... }
}
```

## System information

- Apalache version [`apalache-mc version`]: 0.25.6

**Comment by Kukovec** [comment]
This is not a parser error per se, `TlaAssumeDecl` doesn't even have a `name` field in the current IR.

**Comment by fan-tom** [comment]
Hey @bugarela, I want to work on this task, and while trying to naively implement assume name parsing, I stumbled upon the fact that this name is optional, according to the TLA [grammar](http://lamport.azurewebsites.net/tla/TLAPlus2Grammar.tla):
```TLA+
TLAPlusGrammar ==
 LET P(G) ==
   /\ G.Module ::=     AtLeast4("-") 
                   & tok("MODULE") & Name & AtLeast4("-")
                   &   (Nil | (tok("EXTENDS") & CommaList(Name)))
                   &   (G.Unit)^* 
                   &   AtLeast4("=")
   /\ G.Unit ::= 
           ...
           |  G.Assumption 
           ...
   /\ G.Assumption ::=  
          Tok({"ASSUME", "ASSUMPTION", "AXIOM"}) 
             & (Nil | Name & tok("==")) & G.Expression <--- here, Nil | Name
```
Am I looking at the right source for `ASSUME` grammar? If so, how do you see the correct approach to handle an absent name?
`TlaAssumeDecl` inherits from `TlaDecl`, which defines non-optional `name` property.
Currently `TlaAssumeDecl` implements it this way: `"ASSUME" + body.ID`
And it is easy to just use explicitly defined name when parsing a spec, and fallback to current approach when there is no name.
But then we also do tla2json conversion, and I assume we don't want to expose these artificial names there.
Also, another point where we construct `TlaAssumeDecl` is from `QuintAssume`, which already has a `name` field, but comment says it may be '_', which I assume corresponds to an unnamed `ASSUME` clause, am I right?
Given that, seems we also need to preserve whether the name is artificial or not, and take it into account in each place we use it, though we may use it in an abstract context, where decl type is unknown, which makes such approach error-prone. Do we need to detach `assume` clauses from `TlaDect` type hierarchy to avoid such errors, or we can ignore such a possibility for now? WDYT?

**Comment by bugarela** [comment]
Hi @fan-tom, thanks for taking a shot at this!

I don't understand this part very well. I can't picture the error-prone situation you are describing.
> Given that, seems we also need to preserve whether the name is artificial or not, and take it into account in each place we use it, though we may use it in an abstract context, where decl type is unknown, which makes such approach error-prone.

Other than that, I think it is ok to have the artificial names on JSON - I'd say there are more scenarios where that is helpful than scenarios where it is an issue.

@shonfeder do you agree? I feel like my opinion is a bit partial here since I opened this issue because of I problem I had while parsing ApalacheIR from JSON.

**Comment by shonfeder** [comment]
Hi @fan-tom! I'll echo @bugarela in expressing gratitude for your contribution.
It is most welcome :)

One clarifying point re: this excellent question:

> Am I looking at the right source for ASSUME grammar?

iiuc, that is the right source for the TLA<strong>+</strong> grammar, and so it
informs what we can expect coming from SANY and what kinds of output we should
generate if/when we want to produce TLA+, but it is not binding for the
ApalacheIR otherwise. We should just represent things in the ways we need to
track needed information and produce needed the out-formation. (It may be that
this clarification is only needed for myself :)).

> Also, another point where we construct TlaAssumeDecl is from QuintAssume,
which already has a name field, but comment says it may be '_', which I assume
corresponds to an unnamed ASSUME clause, am I right?

You are right! It is analogous to an unnamed assume. Tho in the quint grammar declarations are
uniform, and made "anonymous" by use of a "hole", represented by the `_`. If
you're interested, you can see

https://github.com/informalsystems/quint/blob/d4b7b0f713bb8f1f693aa2454127f96c771b45f0/quint/src/generated/Quint.g4#L28

@bugarela, I agree with @fan-tom in principle: encoding the presence or absence
of a declaration *just* in its string representation is error prone in the sense
that we fall back needlessly to a stringly typed encoding, and more easily risk
information loss and program errors. That said, I also find your reasoning
regarding the current practical impact convincing: I cannot think of case in
which it would be problematic to use the artificial name during serialization.
Of coarse, that is liable to be more of a problem with my capacity for thinking
than with the possible problem space.

Fortunately I think we may be able to record the optionality of the name at the
type level without having to interfere with current class hierarchy. This would
make reasoning about the presence/absence of a defined name more reliable when
needed, but allow any current logic to default to using a synthesized name.

My suggestion is that we change 

https://github.com/informalsystems/apalache/blob/30fe7d44b7aeac34218b6ae120caf3d7ad62a758/tlair/src/main/scala/at/forsyte/apalache/tla/lir/TlaDecl.scala#L60-L70

to

```scala
/**
 * An assumption defined by ASSUME(...)
 * 
 * @param definedName
 *   the optional name used in declaring the assumption.
 * @param body
 *   the assumption body
 */
case class TlaAssumeDecl(definedName: Option[String], body: TlaEx)(implicit typeTag: TypeTag)
    extends TlaDecl with Serializable {
  val name: String = definedName match {
    case None    => "ASSUME" + body.ID
    case Some(n) => n
  }

  override def withTag(newTypeTag: TypeTag): TlaAssumeDecl = TlaAssumeDecl(body)(newTypeTag)
}
```

This will require checking at each point of construction or deconstruction that
we are reasoning correctly about the optional name, but also continue to support 
any code that relies on instances of `TlaDecl` having a `name`.

We can then decide based on principle whether we want the serialization to
produce an artificial name for an anonymous `ASSUME` or whether we want to be
more faithful to the structure of the parsed input.

What do y'all think?
