### ISSUE TITLE
Type concretization for nullary expressions

### ISSUE THREAD

**Issue by konnov** [informalsystems/apalache#1880]
The PR #1878 has surfaced a type concretization bug that was somehow avoiding the post type checker. Consider the following specification:

```tla
-------------------------- MODULE TestPolyNullary ------------------------------
EXTENDS FiniteSets

VARIABLES
    \* @type: Set(Int);
    set

Init ==
    LET \* @type: () => Set(a);
        Empty == {}
    IN
    set = Empty

Next == UNCHANGED set
================================================================================
```

When we run Apalache against #1878, the following bug occurs:

```
unexpected expression: Expected a non-polymorphic type, found: (() => Set(c))
```

This caused by the fact that the operator `Empty` is nullary and thus it remains polymorphic. We should concretize its type, as we are doing it for non-nullary operators.

**Comment by konnov** [comment]
@Kukovec any ideas?

**Comment by Kukovec** [comment]
Snowcat will actually correctly infer the type at the application site. The problem is, you can't automatically backpropagate. Consider this:

```
VARIABLES
    \* @type: Set(Int);
    set1,
    \* @type: Set(Str);
    set2,

LET \* @type: () => Set(a);
        Empty == {}
    IN
    /\ set1 = Empty
    /\ set2 = Empty
```

Now, if this operator wasn't nullary and reached the inliner (or if the `keepNullary` flag was off) , the procedure there should resolve polymorphism while evaluating the application.  The only solution I can come up with is to force-inline nullary polymorphic operators. This should be a relatively minor change to Inliner. We could make this another flag, but it's  probably cleaner if this happens by default and the `keepNullary` flag only applies to monomorphic operators.
