### ISSUE TITLE
Extend ITF format with variable types

### ISSUE THREAD

**Issue by Kukovec** [informalsystems/apalache#2258]
At present, only the variable names and values are recorded. This can be a problem in reconstruction via the typed builder in the presence of empty sets/sequences, because empty collections need type tag annotations in the builder.
Concretely, we should either
1. Change the "vars" field to an object, the keys of which are the variables, and the values of which are string representations of TT1 types, or
2. Add a new field "varTypes" (or similar), with that same info, preserving "vars" as a list, as not to break compatibility.

**Comment by shonfeder** [comment]
I think (1) is a nicer option.

I think this also opens up an opportunity to make the trace much more concise and readable!

At the time ITF was designed I argued against the current data representation, because it's treatment of scalars and compound values is so different: https://github.com/informalsystems/apalache/blob/main/docs/src/adr/015adr-trace.md#discussion

At that time, Igore argued that

> The more regular approach is less concise. In the future, we might want to add a flag that lets the user choose between the regular output and the output proposed in this ADR, which is more ad hoc.

However, if we put the variable types in this header data, then we can get rid of all the `#map` and `#set` tags, cause all that data would be readily available in the variable's types. WDYT?

**Comment by Kukovec** [comment]
Yes, I'm more pro (1) myself, ITF isn't really mature enough where we'd need to care about compatibility IMO.
RE compound types, that's more of an orthogonal discussion, but the `#` values did strike me as odd at the time, I wouldn't mind changing them in the future.

**Comment by shonfeder** [comment]
This will be much easier to communicate and gather feedback on with an example.

Here's a fragment of the current ITF format, as per ADR015:

```json
{
  "#meta": {
    "source": "MC_MissionariesAndCannibalsTyped.tla"
  },
  "vars": [ "bank_of_boat", "who_is_on_bank" ],
  "states": [
    {
      "#meta": { "index": 0 },
      "bank_of_boat": "E",
      "who_is_on_bank": {
        "#map": [
          [ "E", { "#set": [ "c1_OF_PERSON", "c2_OF_PERSON",
                             "m1_OF_PERSON", "m2_OF_PERSON" ] } ],
          [ "W", { "#set": [] } ]
        ]  
      }
    },
    {
      "#meta": { "index": 1 },
      "bank_of_boat": "W",
      "who_is_on_bank": {
        "#map": [
          [ "E", { "#set": [ "c1_OF_PERSON", "m1_OF_PERSON" ] } ],
          [ "W", { "#set": [ "c2_OF_PERSON", "m2_OF_PERSON" ] } ]
        ]  
      }
    }
   ]
}
````

Note the way that maps and sets are marked with the `#` prefixed tags. That empty set in the `W` bank of the first state is the kind of problem @Kukovec is pointing out.

The alternative representation using variable-typing info:

```json
{
  "#meta": {
    "source": "MC_MissionariesAndCannibalsTyped.tla"
  },
  "vars": { "bank_of_boat": "Str", "who_is_on_bank": "{ Str : Set(PERSON) }" },
  "states": [
    {
      "#meta": { "index": 0 },
      "bank_of_boat": "E",
      "who_is_on_bank": {
        "E": ["c1_OF_PERSON", "c2_OF_PERSON", "m1_OF_PERSON", "m2_OF_PERSON"],
        "W": []
      }
    },
    {
      "#meta": { "index": 1 },
      "bank_of_boat": "W",
      "who_is_on_bank": {
        "E": ["c1_OF_PERSON", "m1_OF_PERSON"],
        "W": ["c2_OF_PERSON", "m2_OF_PERSON"]
      }
    }
  ]
}
```

IMO, this is a huge win for readability, for humans and for computers! Having to inspect each data type to see whether it has a special tag or not, then inferring it's type based on this always sounded like a big PITA to me.

> that's more of an orthogonal discussion

I think it is parallel, and maybe even coincident, rather than orthogonal :D

**Comment by shonfeder** [comment]
> ITF isn't really mature enough where we'd need to care about compatibility IMO.

I think this is true as well, also if there are large sets of traces being used somewhere, a migration script should be fairly trivial.

(3) A third option of course is just to infer the type of empty collections from non-empty ones in the same trace. If that cannot be done, we could either throw an error or fall back to some other inference mechanism.

If we pursue (1) or (2) it really makes the odd `#` tags redundant, so I think we should seriously consider coupling these changes. Still, we can introduce them as separate changes, giving us time to get Igor's feedback and perhaps feedback from MBT.

**Comment by shonfeder** [comment]
Yeah, I agree (3) seems unappealing. Even more so to me given that (1) and (2) solve other problems whereas (3) introduces new problems :D

**Comment by shonfeder** [comment]
The types given in the variable should JSON serialized, not using our human notation, otherwise all code consuming ITF would need to be able to parse our type specification syntax.

**Comment by Kukovec** [comment]
> Should the types given in the variable should JSON serialized, not using our human notation? Otherwise all code consuming ITF would need to be able to parse our type specification syntax.

Are you asking if we want a JSON tree-like structure for compound TT1 types, e.g. `Str -> Int` (`= FunT1(StrT1,IntT1)` written as 
```json
"type": {
  "kind": "FunT1"
  "args": {
    "from": "StrT1"
    "to": "IntT1"
  }
}
```
or something similar? Or is the question just whether the type written in the ITF file is `Str -> Int` or `FunT1(StrT1,IntT1)`?

**Comment by shonfeder** [comment]
Yeah, I'm thinking we should use the same encoding for types as is generated by our json serialization of IR.

Whether we intend to only use these in Apalache or whether we depend to direct users to refer to these to interpret the values in variables, it seems like it's most sensible if we use a serialized representation of the types rather than requiring another parsing pass.

**Comment by Kukovec** [comment]
I've spun up a new issue for the fields. This one will be closed with just the `"vars"` change, but we can discuss the rest under the new issue.

**Comment by Kukovec** [comment]
After a discussion we agree to go forward with the following:
 - Types in ITF traces are _optional_ in general, so the `variables` field should remain unchanged
 - Types in ITF traces _for Apalache use_ are mandatory and must be present in `#meta`.
