### ISSUE TITLE
Add support for Quint type definitions

### ISSUE THREAD

**Issue by shonfeder** [informalsystems/apalache#2589]
We are currently ignoring quint type definitions

https://github.com/informalsystems/apalache/blob/a4f1694df4819dc42f7046d93bcfe4d78ca98f93/tla-io/src/main/scala/at/forsyte/apalache/io/quint/Quint.scala#L660-L662

This is based on the (as it turns out) incorrect assumption that Quint typedefs get inlined. However, type aliases are not. So we need to translate those into our Apalache IR conversion.

**Comment by bugarela** [comment]
Closing in favor of https://github.com/informalsystems/quint/issues/976
We decided to inline typedefs in Quint afterall.

**Comment by thpani** [comment]
For the historians: We agreed offline that it's better to do type inlining on the Quint side. Reasoning:

* There’s no great type inlining support in Apalache. The inliner lives in Snowcat, and the interface is half-baked (takes annotation comments as input). Using it would either blow up the Quint translation or require a major refactoring of the typechecker.
* Apalache's type inliner lives in snowcat, but we may want to skip it in the future, since we’re already typechecking in Quint.
* For a future where there’s additional analysis tools for Quint, it makes sense to implement type inlining once, in Quint.

**Comment by shonfeder** [comment]
Awesome! Happy to see this complexity moved out of Apalache :) nice work!
