### ISSUE TITLE
Tool output in JSON format for integration

### ISSUE THREAD

**Issue by andrey-kuprianov** [informalsystems/apalache#529]
For Apalache to be used in integration with other tools, in particular with MBT, it is important to have an option to provide the tool output in a machine-parsable format; JSON seems to be good for that, as the accepted interoperability format.

The proposal is to add `--json` option to the tool; with this option _all output_ of the tool, including exceptions, that goes to the standard output, needs to be formatted as a valid JSON.

**Comment by konnov** [comment]
This is related to #107. As @shonfeder suggested, we should not implement these two features separately. A good solution would be to introduce a common data structure and write the output with a template engine in the spirit of MVC. Though we have to understand how to make such output interactive.

**Comment by konnov** [comment]
@andrey-kuprianov is this issue still relevant for the integration with MBT? You are using both TLC and Apalache, and TLC does not give you JSON output.

**Comment by konnov** [comment]
I guess, it will be irrelevant, if we have #730, right?

**Comment by lemmy** [comment]
FWIW: The `Json.tla` module does provide a flexible method to output TLA+ values and [error-traces](https://github.com/tlaplus/Examples/blob/master/specifications/ewd840/EWD840_json.tla) in Json ([screencast](http://tla.msr-inria.inria.fr/kuppe/TLC-Json.gif)).  https://github.com/japgolly/tla2json is a standalone tool to convert a trace to Json.

**Comment by konnov** [comment]
> FWIW: The `Json.tla` module does provide a flexible method to output TLA+ values and [error-traces](https://github.com/tlaplus/Examples/blob/master/specifications/ewd840/EWD840_json.tla) in Json ([screencast](http://tla.msr-inria.inria.fr/kuppe/TLC-Json.gif)). https://github.com/japgolly/tla2json is a standalone tool to convert a trace to Json.

Yep. I guess, Andrey wanted to have a JSON protocol for the tool output.

**Comment by konnov** [comment]
I think it makes more sense to define a server protocol, instead of trying to wrap the tool output in json.

**Comment by lemmy** [comment]
I agree about not wrapping the tool output, which is why I've been trying to push this functionality into TLC/TLA+.  To me, this provides the most flexibility and keeps users from learning additional tools such as `jd`.  Could you explain what would constitute the server protocol?  Perhaps, Apalache and TLC could provide something compatible.

**Comment by konnov** [comment]
We do not have a precise idea yet. The server should serve model checking queries and their results, e.g., for tests that are discussed in [RFC006](https://apalache.informal.systems/docs/adr/006rfc-unit-testing.html). I guess, you are already doing something similar for the cloud version.

**Comment by shonfeder** [comment]
I think this has been subsumed by #1025?

I can add that, as a general principle, I don't think it's always useful to put human readable output into machine readable forms, so just putting Apalache output into a JSON object doesn't seem that useful. Our current output has lots of stuff that might be useful or fun for a human, but is really just noise for machine readable purposes. Useful machine encoding of output would involve reworking all of the output with a coherent and principled data model directing how we encode the output data. But this process is prerequisite for the server-mode, which is focused on providing the kinds of output which other programs need in order to interoperate with and benefit from the features Apalache has to offer.
