### ISSUE TITLE
[FEATURE] Refactor ReplaceFixed

### ISSUE THREAD

**Issue by konnov** [informalsystems/apalache#566]
How about the following refactoring:

1. Instead of the object, introduce a class that received `TransformationTracker` as a constructor parameter. You can also introduce a companion object for convenience.

2. The method `apply` of class `at.forsyte.apalache.tla.lir.transformations.standard.ReplaceFixed` has the following signature:

```scala
  def apply(
      replacedEx: TlaEx,
      newEx: => TlaEx,
      tracker: TransformationTracker
  ): TlaExTransformation
```

By doing step 1, we can get rid of `tracker`. I would also prefer having a matching predicate (maybe even a partial function?) instead of a concrete expression, that is:

```scala
  def apply(
      needsReplacement: TlaEx => Boolean,
      replaceWithEx: => TlaEx
  ): TlaExTransformation
```

**Comment by Kukovec** [comment]
We can easily do 1. As for 2, there used to be a more general "ReplacePattern" (or something of the sort) transformation, but we got rid of it because it wasn't being used. Basically, `ReplaceFixed` is a substitution operation for instantiating operators, whereas there are currently no cases where we would need to replace a family of expressions with the same expression. Unless you have a concrete need for this, I don't see the point.

**Comment by konnov** [comment]
I don't remember exactly why we did it, but it's probably because all expressions to be replaced were of the form `NameEx(_)`. If it still the case, let's keep it.

**Comment by konnov** [comment]
Actually, I just hit this problem in #561. With the current signature I have to pass `NameEx(...)` including the type tag. It would be much better to have a predicate there, as I actually do not care about the type tag.
