### ISSUE TITLE
[FEATURE] Move at.forsyte.apalache.tla.lir.io to tla-import

### ISSUE THREAD

**Issue by konnov** [informalsystems/apalache#784]
We shall move all classes `at.forsyte.apalache.tla.lir.io` to `tla-import` under the package `at.forsyte.apalache.io`. @Kukovec do you like to do it? I think we should consolidate all of input/output in `tla-import`.

**Comment by Kukovec** [comment]
Looking into this, I don't think it is a good idea to move everything. The problem is, `lir` is a lower-level package than `io`, so things like the `TlaEx` printer have to live in the `lir` package, and cannot move. That said, we can certainly move a decent number of classes, but given that we'd be stuck with `lir`-io subpackages in both modules, I'm not sure if there's a real benefit.

**Comment by Kukovec** [comment]
Follow up: We'll move everything except the `Printer`, which will get moved in a future PR, when `TlaEx.toString` is reworked.
