### ISSUE TITLE
Confusing error message on missing semicolon in type

### ISSUE THREAD

**Issue by jtremback** [informalsystems/apalache#954]
I forgot a semicolon on a type annotation and received this error message:

`Typing input error: Unexpected annotation of action: @type`

Here is the faulty code:

```
VARIABLES 
    \* mapping from chain id to its data
    \* @type: Str -> CHAIN;
    chains,

    \* last action performed
    \* @type: ACTION
    action,

    \* string with the outcome of the last operation
    \* @type: Str;
    actionOutcome
```

IMO this error message was unclear because it did not say anything about the semicolon problem. However, it was good that it mentioned `action`.

**Comment by shonfeder** [comment]
Thank you for the report! 

This was first reported in  #802, but we can leave this as a factored out subissue.

**Comment by jtremback** [comment]
I see, it is a duplicate

**Comment by shonfeder** [comment]
Its helpful to have more detail, and also #802 is kind of a meta-issue, cause it lists a bunch of little things. It's helpful to have this factored out into its own item. :+1:

**Comment by konnov** [comment]
Although this has been fixed we have found that TLA+ Toolbox generates comments that look exactly like malformed annotations with a missing `;` in the end. So I guess the only reasonable action here is to ignore such malformed annotations and issue a warning instead of an error. This will bring us back to the degraded usability :(
