### ISSUE TITLE
Replace `\cup` with `\union` in the documentation

### ISSUE THREAD

**Issue by shonfeder** [informalsystems/apalache#974]
There are numerous places in [the docs](https://github.com/informalsystems/apalache/tree/unstable/docs/) where we use the `\cup` syntax for TLA+'s set union operator instead of the clearer (and our preferred) `\union`.

Let's replace all occurrences of `\cup` in the docs with `\union`. This should be relatively quick to accomplish using `sed` or an editor's find/replace functionality.

After fixing the docs, be sure to build the documentation locally (see [the README.md](https://github.com/informalsystems/apalache/tree/unstable/docs/README.md) to make sure stuff looks as expected in general.

**Comment by rodrigo7491** [comment]
Should `\cup` still be present in the definition of set union (cf. [sets.md](https://github.com/informalsystems/apalache/blob/unstable/docs/src/lang/sets.md) and [standard-operators.md](https://github.com/informalsystems/apalache/blob/unstable/docs/src/lang/standard-operators.md))? Since `\cap` is still there, I think it makes sense to leave it.

**Comment by shonfeder** [comment]
Ah yes! Good catch. We don’t to remove it in places where we are explaining to users what it is directly, just in places where we could as well use either cup or union.
