### ISSUE TITLE
[FEATURE] Enumerate module files in `x/`

### ISSUE THREAD

**Issue by Kukovec** [informalsystems/apalache#993]
Currently, intermediate module states are written to `x/<FOLDER>/`, with names corresponding to pass names, e.g. `OutInline`, `OutPostTypeCheckerSnowcat`, etc. To understand the order in which the files were produced, one currently needs to have internalized the Apalache pass order (which changes as new passes are added or removed anyhow). 
It would be much more helpful, if the filenames reflected the pass order, i.e. if files were prefixed by the number of the pass, in which they were generated, e.g. `05_OutInline`, `12_OutPostTypeCheckerSnowcat`, `99_XYZ`.

Currently, the order is (as defined by `CheckerModule`):
```
PASS #0: SanyParser
PASS #1: TypeCheckerSnowcat
PASS #2: ConfigurationPass
PASS #3: DesugarerPass
PASS #4: UnrollPass
PASS #5: InlinePass
PASS #6: PrimingPass
PASS #7: VCGen
PASS #8: PreprocessingPass
PASS #9: TransitionFinderPass
PASS #10: OptimizationPass
PASS #11: AnalysisPass
PASS #12: PostTypeCheckerSnowcat
PASS #13: BoundedChecker
PASS #14: Terminal                                  
```

**Comment by rodrigo7491** [comment]
Most pass names are hard coded, so they can be simply prefixed with a number. Since `PostTypeCheckerSnowcat` inherits from `TypeCheckerSnowcat`, a new protected field is needed in [EtcTypeCheckerPassImpl](https://github.com/informalsystems/apalache/blob/unstable/tla-types/src/main/scala/at/forsyte/apalache/tla/typecheck/passes/EtcTypeCheckerPassImpl.scala). In order to not hard code the numbers, I think a change to [Pass](https://github.com/informalsystems/apalache/blob/unstable/mod-infra/src/main/scala/at/forsyte/apalache/infra/passes/Pass.scala) would be needed, but based on what we discussed I wont go there.

@Kukovec Passes `BoundedChecker` and `Terminal` don't seem to produce intermediary module's files, is this correct or am I missing something?

**Comment by Kukovec** [comment]
> BoundedChecker and Terminal don't seem to produce intermediary module's files, is this correct or am I missing something?

No, that's expected, those don't transform the module anymore.
